{
 "title": "Disk Monitoring",
 "tags": [ "prometheus" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Filesystem tracking",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "((1 - node_filesystem_avail_bytes{job=\"svr88\"} / node_filesystem_size_bytes{job=\"svr88\"}) * 100)",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Read & Write Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{job=\"svr88\"}[5m]) / rate(node_disk_reads_completed_total{job=\"svr88\"}[5m]) * 100",
     "legendFormat": "{{ device }} disk read latency"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{job=\"svr88\"}[5m]) / rate(node_disk_writes_completed_total{job=\"svr88\"}[5m]) * 100",
     "legendFormat": "{{ device }} disk write latency"
    }
   ]
  },
  {
   "title": "Number of inodes on our system",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "node_filesystem_files_free{job=\"svr88\"} / node_filesystem_files{job=\"svr88\"} * 100",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Overall I/O load on your instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 1, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_now{job=\"svr88\"}[5m])",
     "legendFormat": "{{ device }} global I/O"
    }
   ]
  }
 ]
}